.PHONY: install build serve clean

# Install all dependencies
install:
	pnpm install

# Build
build:
	pnpm run build

# Run development server
serve:
	pnpm run serve

# Clean build artifacts
clean:
	rm -rf dist node_modules
