/**
 * Skybolt cache loader
 * Loads required assets from the Skybolt cache (localStorage)
 * 
 * Exports: window.Skybolt
 * 
 * Cached assets can be inserted by adding a tag with the attribute `sb-state="load"`
 * and the correct `sb-type`, `sb-name`, and `sb-version` attributes.
 * 
 * Scripts/modules:
 *   <meta sb-state='load' sb-type='script' sb-name='boot' sb-version='Fhwa4p'>
 * 
 * Stylesheets are supported too:
 *   <meta sb-state='load' sb-type='style' sb-name='default' sb-version='FFJg-n'>
 * 
 * And HTML fragments:
 *   <meta sb-state='load' sb-type='fragment' sb-name='header' sb-version='PgpDxo'>
 * 
 * Versions are hashes generated by the Skybolt server and are used to invalidate the cache
 * 
 * TODO: Simplify the syntax - maybe `sb-load-script="boot:Fhwa4p"` and `sb-load-style="default:FFJg-n"` and `sb-load-fragment="header:PgpDxo"`
 *
 * @author Jens Roland
 * @version 1.0.0
 */

var Skybolt = (function (window, document, localStorage) {

	this.assetMap = {};

	var baseUrl = '/assets/js/',  // TODO: Make this configurable
	    localStorageCacheKey = 'sbCache',
	    loaderScriptName = 'skybolt-load',
	    dataNameAttr = 'sb-name',
	    dataVersionAttr = 'sb-version',
	    dataSkyboltAttr = 'sb-state';

	// Self destruct / nuke caches from orbit
	// Activated in case the client cache is deleted or corrupted
	function selfdestruct() {
		localStorage.removeItem(localStorageCacheKey);
		document.cookie = 'cachebuster=true';
		location.reload();
	}

	// Cache loading
	// Retrieve necessary assets from localStorage cache, and insert them where needed
	this.loadFromCache = function(elements) {
		// First, we create an array of 'unrendered content' meta tags
		// (converting the NodeList returned by querySelectorAll)
		elements = elements || document.querySelectorAll('['+dataSkyboltAttr+'="load"]');
		var metaTags = [];
		for(var i = elements.length; i--; metaTags.unshift(elements[i])){};

		// Then we iterate over the array and replace the meta tags by the corresponding cached content
		for (var i = 0, len = metaTags.length; i < len; i++) {
			var metaTag = metaTags[i];

			var attr = metaTag.attributes,
			    name = attr[dataNameAttr].value,
			    version = attr[dataVersionAttr].value,
			    item = this.assetMap[name];
			if (typeof item === 'undefined' || item.version !== version || (item.data.length !== item.size && item.size != 0)) {
				// TODO: If an asset is simply missing, loadAsync it and cache it again
				selfdestruct();
				return;
			}
			var elm = document.createElement(item.type == 'fragment' ? 'div' : item.type);
			elm.innerHTML = item.data;
			elm.setAttribute(dataNameAttr,name);
			elm.setAttribute(dataSkyboltAttr, 'loaded');
			metaTag.parentNode.replaceChild(elm, metaTag);
		}
	}

	// Cache this script
	// Fetch cache loader JS file from server without executing it, to prime the client cache
	function loadSelfIntoCache(version) {
		var xhr = new XMLHttpRequest();
		xhr.onreadystatechange = function () {
			if (xhr.readyState === 4) {
				if (xhr.status === 200 || xhr.status === 304) {
					// Fix memory leak in IE
					xhr.onreadystatechange = function(){};
					// When the cacheloader is in the browser cache, we set a cookie to inform the server
					document.cookie = 'loadercached=' + version;
				}
			}
		};
		xhr.open('GET', baseUrl+version+'/'+loaderScriptName+'.js');
		xhr.send();
	}



	// Initialization logic

	// Try to pull up the existing cached assets
	var cacheJSON = localStorage.getItem(localStorageCacheKey);
	if (cacheJSON !== null) {
		try {
			this.assetMap = JSON.parse(cacheJSON);
		} catch (err) {
			selfdestruct();
		}
	}
	
	// Load <head> assets from cache immediately (when loaded via script tag it executes after the DOMReady event fired)
	this.loadFromCache();
	// And once the DOM is ready (when inlined, the immediately-executed one can't find any elements yet)
	document.addEventListener('DOMContentLoaded', () => {
		Skybolt.loadFromCache();
	});

	// If the loader script itself was inlined, we fetch and cache the file once the client is idle
	// TODO: Use requestIdleCallback if available: https://caniuse.com/requestidlecallback
	var inlinedLoader = document.querySelector('['+dataNameAttr+'='+loaderScriptName+']');
	if (inlinedLoader) {
		window.addEventListener('load', function(){
			setTimeout(function(){
				loadSelfIntoCache(inlinedLoader.attributes[dataVersionAttr].value);
			}, 4096);
		}, false);
	}

	return this;

}(window, document, localStorage));
