/**
 * Skybolt cache loader
 * Loads required assets from the Skybolt cache (localStorage)
 * 
 * Exports: window.Skybolt
 * 
 * Cached assets can be inserted by adding a tag with the attribute `sb-state="load"`
 * and the correct `sb-asset` attribute.
 * 
 * Scripts/modules:
 *   <meta sb-state='load' sb-asset='boot:script:Fhwa4p'>
 * 
 * Stylesheets are supported too:
 *   <meta sb-state='load' sb-asset='default:style:FFJg-n'>
 * 
 * And HTML fragments:
 *   <meta sb-state='load' sb-asset='header:fragment:PgpDxo'>
 * 
 * Versions are hashes generated by the Skybolt server and are used to invalidate the cache
 *
 * @author Jens Roland
 * @version 1.0.0
 */

var Skybolt = (function (window, document, localStorage) {

	console.log(`Skybolt cache loader initializing...`);

	this.assetMap = {};

	var baseUrl = '/assets/js/',  // TODO: Make this configurable
	    localStorageCacheKey = 'sbCache',
	    loaderScriptName = 'skybolt-load',
	    assetAttr = 'sb-asset',
	    stateAttr = 'sb-state';

	// Self destruct / nuke caches from orbit
	// Activated in case the client cache is deleted or corrupted
	function selfdestruct() {
		console.log(`Self-destructing cache...`);
		localStorage.removeItem(localStorageCacheKey);
		document.cookie = 'cachebuster=true';
		location.reload();
	}

	// Cache loading
	// Retrieve necessary assets from localStorage cache, and insert them where needed
	this.loadFromCache = function(elements) {
		console.log(`loadFromCache invoked`);
		// First, we create an array of 'unrendered content' meta tags
		// (converting the NodeList returned by querySelectorAll)
		elements = elements || document.querySelectorAll('['+stateAttr+'="load"]');
		if ( ! elements.length) {
			console.log(`Skipped: No assets found to load from cache.`);
			return;
		}

		var metaTags = [];
		for(var i = elements.length; i--; metaTags.unshift(elements[i])){};

		// Then we iterate over the array and replace the meta tags by the corresponding cached content
		for (var i = 0, len = metaTags.length; i < len; i++) {
			var metaTag = metaTags[i];

			var attr = metaTag.attributes,
				skyboltAttribute = attr[assetAttr].value,
				[ name, type, version ] = skyboltAttribute.split(':'),
			    item = this.assetMap[name];
			if (typeof item === 'undefined' || item.type !== type || item.version !== version || (item.data.length !== item.size && item.size != 0)) {
				console.error(`Invalid asset meta tag found:`, metaTag, item);
				// TODO: If an asset is simply missing, loadAsync it and cache it again
				selfdestruct();
				return;
			}
			var elm = document.createElement(item.type == 'fragment' ? 'div' : item.type);
			elm.innerHTML = item.data;
			elm.setAttribute(assetAttr, skyboltAttribute);
			elm.setAttribute(stateAttr, 'loaded');
			metaTag.parentNode.replaceChild(elm, metaTag);
			console.log(`The ${type} '${name}' was loaded from cache.`);
		}
	}

	// Cache this script
	// Fetch cache loader JS file from server without executing it, to prime the client cache
	function loadSelfIntoCache(version) {
		var xhr = new XMLHttpRequest();
		xhr.onreadystatechange = function () {
			if (xhr.readyState === 4) {
				if (xhr.status === 200 || xhr.status === 304) {
					// Fix memory leak in IE
					xhr.onreadystatechange = function(){};
					// When the cacheloader is in the browser cache, we set a cookie to inform the server
					document.cookie = 'loadercached=' + version;
					console.log(`Loader cached itself with version ${version}.`);
				}
			}
		};
		xhr.open('GET', baseUrl+version+'/'+loaderScriptName+'.js');
		xhr.send();
	}



	// Initialization logic

	// Try to pull up the existing cached assets
	var cacheJSON = localStorage.getItem(localStorageCacheKey);
	if (cacheJSON !== null) {
		try {
			this.assetMap = JSON.parse(cacheJSON);
		} catch (err) {
			selfdestruct();
		}
	}
	
	// Load <head> assets from cache immediately (when loaded via script tag it executes after the DOMReady event fired)
	this.loadFromCache();
	// And once the DOM is ready (when inlined, the immediately-executed one can't find any elements yet)
	document.addEventListener('DOMContentLoaded', () => {
		console.log(`DOM ready`);
		Skybolt.loadFromCache();
	});

	// If the loader script itself was inlined, we fetch and cache the file once the client is idle
	// TODO: Use requestIdleCallback if available: https://caniuse.com/requestidlecallback
	var inlinedLoader = document.querySelector('[sb-asset^=\''+loaderScriptName+':\']');
	if (inlinedLoader) {
		window.addEventListener('load', function(){
			setTimeout(function(){
				const [ name, version ] = inlinedLoader.getAttribute(assetAttr).split(':');
				loadSelfIntoCache(version);
			}, 4096);
		}, false);
	}

	return this;

}(window, document, localStorage));
