/**
 * Skybolt cache builder
 * Stores inlined assets in the Skybolt cache (localStorage)
 * 
 * Exports: nothing, just runs the IIFE
 * 
 * Inlined assets can be cached by adding `sb-state="load"` to the tag
 * and the corresponding `sb-type`, `sb-name`, and `sb-version` attributes.
 * 
 * Scripts/modules:
 *   <script sb-type='script' sb-name='counter' sb-version='rGu4co' sb-state='store'>
 *       // Script/module code inlined here...
 *   </end script tag>
 * 
 * Stylesheets are supported too:
 *   <style sb-type='style' sb-name='default' sb-version='FFJg-n' sb-state='store'>
 *       body { background-color: lime; }
 *   </style>
 * 
 * And HTML fragments:
 *   <div sb-type='fragment' sb-name='header' sb-version='PgpDxo' sb-state='store'>
 *       <div class="header">
 *           Skybolt Technology Demo
 *       </div>
 *   </div>
 * 
 * Versions are hashes generated by the Skybolt server and are used to invalidate the cache
 * 
 * TODO: Support omitting the `sb-type`	attribute and infer it from the tag name
 * TODO: Simplify the syntax - maybe `sb-state="store"` paired with `sb-asset="counter:rGu4co"`
 * 
 * @author Jens Roland
 * @version 1.0.0
 */

;(function (window, document, localStorage) {

	console.log(`Skybolt cache builder initializing...`);

	var baseUrl = '/assets/js/',  // TODO: Make this configurable
	    assetCookieName = 'assets',
	    localStorageCacheKey = 'sbCache',
	    dataSkyboltAttr = 'sb-state',
	    inventoryCookieRegex = /(^|;)\s*inventory\s*=/,
	    versions = {};

	// Cache storage
	// Store inlined assets to localStorage cache
	var storeToCache = function (elements) {
		elements = elements || document.querySelectorAll('['+dataSkyboltAttr+'="store"]');
		if ( ! elements.length) {
			console.log(`Skipped: No assets found to store in cache.`);
			return;
		}

		for (var i = 0, len = elements.length; i < len; i++) {
			var e = elements[i],
			    attr = e.attributes,
				skyboltAttribute = attr['sb-asset'].value,
				[ itemName, itemVersion ] = skyboltAttribute.split(':'),
			    itemType = { 'script': 'script', 'style': 'style', 'div': 'fragment' }[e.tagName.toLowerCase()],
			    itemData = e.innerHTML,
			    item = {
					type: itemType,
					version: itemVersion,
					data: itemData
				};

			// Add SourceURL to stored scripts
			// See: http://blog.getfirebug.com/2009/08/11/give-your-eval-a-name-with-sourceurl/
			if (itemType == 'script') item.data += '\n//@ sourceURL=' + baseUrl + itemVersion + '/' + itemName + '.js';
			item.size = item.data.length;

			Skybolt.assetMap[itemName] = item;
			versions[itemName] = itemVersion;
			e.setAttribute(dataSkyboltAttr, 'stored');
			console.log(`The ${itemType} '${itemName}' was stored to cache.`);
		}

		document.cookie = assetCookieName + '=' + JSON.stringify(versions);
		localStorage.setItem(localStorageCacheKey, JSON.stringify(Skybolt.assetMap));
	};

	// Inventory reporting
	// Post localStorage cache 'inventory' to server
	function reportInventory() {
		document.cookie = assetCookieName + '=' + JSON.stringify(versions);
	}

	// Store inlined assets
	storeToCache();

	// If the server requested an inventory report, we send it	
	if (inventoryCookieRegex.test(document.cookie)) {
		console.log(`Server requested an asset inventory, preparing to send it...`);
		reportInventory();
	}

}(window, document, localStorage));
