name: Split Go Package
run-name: Push to Go repo for ${{ github.ref }}

on:
  push:
    branches:
      - main
    paths:
      - 'packages/go/**'

jobs:
  split:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Split and push to skybolt-go repo
        uses: cpina/github-action-push-to-another-repository@main
        env:
          SSH_DEPLOY_KEY: ${{ secrets.GO_PACKAGE_DEPLOY_KEY }}
        with:
          source-directory: 'packages/go'
          user-email: 'mail@jensroland.com'
          destination-github-username: 'JensRoland'
          destination-repository-name: 'skybolt-go'
          target-branch: main
          create-target-branch-if-needed: true
          commit-message: 'Sync from monorepo: ${{ github.sha }}'
